travis:
  secure:
    BINSTAR_TOKEN: 6RJgTKtApTAz1krAaVjePeFYty4OfxrAyWD1GRkdMt0UacSxBFA7ts7f0EKx1T3+XGgIjFfhf3BLz7Mff0RLEWq8iBt1d7/zc0YdwBqdl/zELX1JuZtVCwNklbISQm35FIEeF2SuQgrG8NSV/TOdgziHlS2waQMtXXPIbzwQx8Zs7N2K40AeetZKJ/eY+d8U7JihpXZhHl8y6AsSsc9DXpk9B8or6a6I+bI2j7pm59WiVtekrnIiGCxgMORCwckiVLE2UEnxQWSHPwXHMeK1SOzWmy+IchW4paLcXLLzrgNalP09+daqB25yeRjuQLvRDp56aGDpMVj1DSSEoiSIARJKMwws0wjKmY62OZ/HRnw13dKIeNaTaV7DHfxRDMVQa3tWOz85AAi944NwBVLzgJkwSMdVifbsH1lo9KzjQusEnO78M5z1retSeThvFv48LxigKANvTgigFMTV0+MS2j404nlIaoVwyWOLJDDiXfonSSgd3KBEjmL/nZtvr2RdrTz+xoU93sevQlnIVgayRCxhhmUqC+t96fmsGbUFky0jQ9Ah+GfwDcr61HntqTY7lX6ThZwoKLFK/8pgemrP9FOYngna0uxZGWxEQjV/1powNETzGidJwid0q2Vuw8XusagmNZk4ug6Rxe56NTEkWGkimpoPp+VvJ/FbZelZdeA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
